server: 
  port: 8080
spring: 
  application:  
    name: blog
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog?characterEncoding=UTF8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8